//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pntlession09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PntKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PntKhoa()
        {
            this.PntSinhViens = new HashSet<PntSinhVien>();
        }
    
        public string PntMakh { get; set; }
        public string PntTenKH { get; set; }
        public Nullable<bool> PntTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PntSinhVien> PntSinhViens { get; set; }
    }
}
