//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pntlession09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PntSinhVien
    {
        public string PntMaSV { get; set; }
        public string PntSV { get; set; }
        public string PntTenSV { get; set; }
        public Nullable<System.DateTime> PntNgaySinh { get; set; }
        public Nullable<bool> PntPhai { get; set; }
        public string PntPhone { get; set; }
        public string PntEmail { get; set; }
        public string PntMakh { get; set; }
    
        public virtual PntKhoa PntKhoa { get; set; }
    }
}
